export const SET_QUOTE = 'SET_QUOTE'
export const SET_LOADING = 'SET_LOADING'
export const SEND_ORDER = 'SEND_ORDER'
export const SET_MESSAGE = 'SET_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'

export const SUCCESS = 'SUCCESS'
export const ALERT = 'ALERT'
export const BUY = 'BUY'
export const SELL = 'SELL'
